# github --> dacioms/DacioFeature3_24

In [1]:
!pip install -r requirements.txt


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# A. Manipular dados numéricos para algoritmos de Machine Learning

## A.1. Explicar o que é uma feature e a sua relação com os modelos de machine learning

Uma feature, ou característica, é uma variável de entrada usada por um modelo de machine learning para fazer previsões ou tomar decisões. As features são essenciais porque carregam a informação a partir da qual o modelo aprende. Em termos mais práticos, as features podem ser vistas como colunas em uma tabela de dados, onde cada coluna representa um tipo específico de informação (como altura, peso, idade, etc.) que pode ser usada para prever um resultado (como o risco de uma doença, a classificação de um documento, etc.). A escolha e a qualidade das features influenciam diretamente o desempenho do modelo.

## A.2. Explicar o que são escalares, vetores e espaços

- **Escalares:** Um escalar é um único número real ou complexo. Em machine learning, um escalar pode representar uma única medida ou valor, como a temperatura em um dado dia.
  
- **Vetores:** Um vetor é uma sequência de números (escalares) dispostos em uma determinada ordem. Em machine learning, vetores são frequentemente usados para representar exemplos de dados. Por exemplo, um vetor pode representar as características (features) de um paciente, como [idade, peso, pressão arterial].
  
- **Espaços:** Um espaço, especificamente um espaço vetorial, é um conjunto de vetores que podem ser adicionados uns aos outros e multiplicados por escalares para formar novos vetores dentro do mesmo espaço. Em machine learning, o espaço vetorial das features é onde as operações de modelagem acontecem. Este espaço pode ser de alta dimensão dependendo do número de features usadas.

## A.3. Realizar discretização de variáveis contínuas por meio de quantização com bins fixos

A discretização de variáveis contínuas é o processo de converter variáveis contínuas em variáveis discretas dividindo o intervalo contínuo em partes distintas chamadas "bins". Isso pode ser feito de várias maneiras, uma das quais é utilizando bins de largura fixa.

**Exemplo em Python:**

In [2]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com bins de largura fixa
bins = np.linspace(0, 100, 11)  # 10 bins de largura 10
labels = [f'Bin {i}' for i in range(1, len(bins))]
dados_discretizados = pd.cut(dados, bins=bins, labels=labels)

print(dados_discretizados)

['Bin 7', 'Bin 8', 'Bin 6', 'Bin 2', 'Bin 10', ..., 'Bin 10', 'Bin 10', 'Bin 8', 'Bin 5', 'Bin 3']
Length: 100
Categories (10, object): ['Bin 1' < 'Bin 2' < 'Bin 3' < 'Bin 4' ... 'Bin 7' < 'Bin 8' < 'Bin 9' < 'Bin 10']


A.4. Realizar discretização de variáveis contínuas por meio de quantização com bins variáveis

A discretização com bins variáveis, ou "quantiles", divide os dados em intervalos de tal forma que cada bin contém aproximadamente o mesmo número de pontos de dados.

**Exemplo em Python:**

In [3]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com quantiles
dados_discretizados = pd.qcut(dados, q=10, labels=False)

print(dados_discretizados)

[5 4 4 2 3 4 4 1 4 6 3 9 5 7 9 7 6 8 6 2 2 3 0 0 5 6 9 3 6 8 3 3 5 8 9 6 4
 2 9 1 2 7 4 0 1 2 0 9 0 1 7 4 5 9 7 7 8 4 7 3 8 2 5 1 0 9 1 6 0 2 2 6 8 8
 5 2 0 0 5 3 5 8 1 6 1 9 6 8 5 7 7 9 1 3 3 0 7 8 1 4]


A.5. Utilizar a FunctionTransformer do sklearn em uma variável

A `FunctionTransformer` permite transformar os dados aplicando uma função customizada. Pode ser útil para aplicar transformações que não estão diretamente disponíveis nas outras classes de transformação do scikit-learn.

**Exemplo em Python:**

In [4]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Dados de exemplo
dados = np.array([[1, 2], [3, 4], [5, 6]])

# Função customizada: quadrado dos valores
transformer = FunctionTransformer(np.square)
dados_transformados = transformer.transform(dados)

print(dados_transformados)

[[ 1  4]
 [ 9 16]
 [25 36]]


A.6. Utilizar a PowerTransformer do sklearn em uma variável

A `PowerTransformer` aplica uma transformação de potência (Box-Cox ou Yeo-Johnson) para estabilizar a variância e tornar os dados mais gaussianos.

**Exemplo em Python:**

In [5]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Dados de exemplo
dados = np.random.rand(100, 1) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar PowerTransformer
pt = PowerTransformer(method='yeo-johnson')
dados_transformados = pt.fit_transform(dados)

print(dados_transformados)

[[-0.21446499]
 [ 0.55291767]
 [-0.60932522]
 [ 0.75696583]
 [-2.04213324]
 [ 1.35538274]
 [-0.87943757]
 [ 0.80827465]
 [-0.39742228]
 [ 1.00528409]
 [-0.68961381]
 [ 0.3865986 ]
 [-0.14983868]
 [ 1.4563869 ]
 [-1.55702704]
 [-0.70080589]
 [-1.26186561]
 [-1.94165681]
 [-0.41085797]
 [-1.69354995]
 [-1.68138496]
 [ 0.03828279]
 [-1.94460035]
 [ 0.30660875]
 [ 1.32410956]
 [ 1.12684846]
 [ 0.92015631]
 [-1.44118781]
 [ 0.46620352]
 [ 1.30053886]
 [ 1.17640226]
 [ 1.22048844]
 [-0.24719714]
 [ 0.22853176]
 [ 1.3190191 ]
 [-1.42844708]
 [ 0.22708303]
 [-0.00216608]
 [ 0.7120111 ]
 [-0.14805818]
 [-0.54252048]
 [ 0.23196783]
 [ 0.98738881]
 [ 0.77165684]
 [-0.77991759]
 [-2.00951522]
 [ 0.46979222]
 [-1.05289065]
 [-0.60636346]
 [-0.38298958]
 [ 0.69838637]
 [ 1.24638306]
 [-1.21202862]
 [-0.53567211]
 [ 0.08731038]
 [ 0.80043033]
 [-1.09048617]
 [-1.14078445]
 [ 1.39607934]
 [-1.04585152]
 [-0.33882662]
 [ 1.23785397]
 [-0.84172178]
 [ 0.84748813]
 [ 1.08157964]
 [-0.24234714]
 [ 0.82046

A.7. Utilizar a normalização Min-Max do sklearn para garantir que os dados estão na mesma faixa-dinâmica

A normalização Min-Max escala os dados para que todos os valores fiquem dentro de um intervalo especificado, geralmente [0, 1].

**Exemplo em Python:**

In [6]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Min-Max Scaler
scaler = MinMaxScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

[[5.61472652e-01 1.00000000e+00]
 [2.95998642e-01 4.06665898e-04]
 [5.23569917e-01 4.61598573e-01]
 [5.83122863e-01 5.52928147e-01]
 [6.22625037e-01 6.95751743e-01]
 [5.51913892e-01 7.09271449e-01]
 [6.34385187e-01 9.09188855e-01]
 [2.73773159e-01 9.00528839e-01]
 [7.08580819e-02 9.07010047e-01]
 [8.52783010e-01 2.50001218e-01]
 [4.37445935e-01 6.01299523e-01]
 [9.92256583e-01 2.75606344e-01]
 [0.00000000e+00 2.09148447e-01]
 [5.06464179e-01 3.95546295e-01]
 [7.43825856e-01 1.38567254e-02]
 [1.34147307e-01 3.44539377e-01]
 [7.81112507e-02 5.81100155e-01]
 [3.52196662e-01 6.52412133e-01]
 [3.45676358e-01 9.51344133e-01]
 [4.78238648e-01 1.17760904e-02]
 [6.43978157e-01 2.22428677e-01]
 [1.90790555e-02 5.28163390e-01]
 [5.65619353e-01 2.75911034e-01]
 [7.08745977e-01 3.45790754e-01]
 [6.76894025e-01 4.32945996e-01]
 [3.86337502e-02 5.29151647e-01]
 [9.47121242e-01 7.72638666e-02]
 [6.58893636e-01 4.59608731e-01]
 [2.38754924e-01 8.10028186e-01]
 [6.60744412e-02 5.37133622e-01]
 [7.033605

A.8. Utilizar a normalização Standard Scaler

A normalização com `StandardScaler` remove a média e escala os dados para que tenham desvio padrão unitário.

**Exemplo em Python:**

In [7]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Standard Scaler
scaler = StandardScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

[[ 1.2577642  -1.63076983]
 [-1.74116728 -1.47502078]
 [-1.74183543 -1.57710461]
 [-1.41342315 -1.39516915]
 [-1.7054062   0.06341939]
 [ 0.57579387  0.89240279]
 [ 1.46258017  0.32965622]
 [-0.15756892  0.39134612]
 [ 0.56208871 -0.45648363]
 [-1.45754339 -1.71177836]
 [ 0.68433695 -0.75223574]
 [ 1.37479187 -1.66442916]
 [-1.4709398  -1.01545739]
 [ 0.95825995  1.04309566]
 [-0.70010044 -0.26418694]
 [-0.10864933 -1.55620877]
 [-1.14026368  0.81630792]
 [-0.34362829 -0.19350138]
 [-0.60154853  1.01461534]
 [-0.14717891 -1.71310896]
 [-1.45094078  1.48592352]
 [-1.3304895   0.76462304]
 [-0.67368209  0.85295612]
 [-0.37369236 -1.09178741]
 [-0.02833043  0.19135633]
 [ 0.46997016  0.47965623]
 [-0.1359915  -0.73057299]
 [ 0.92430623 -0.55571126]
 [ 1.50081564  0.93632524]
 [-0.24979896  1.2009336 ]
 [-0.03398342  1.08148793]
 [-1.02338728 -1.10097438]
 [ 0.34521764 -0.05117123]
 [-0.19944888  1.33891333]
 [-1.02300945 -0.79865303]
 [-0.88567709 -0.81977915]
 [ 0.12709243  1.13067873]
 

A.9. Utilizar a regularização norma-l2

A regularização L2, também conhecida como regularização de Ridge, adiciona uma penalidade igual ao quadrado da magnitude dos coeficientes ao objetivo de otimização.

**Exemplo em Python:**

In [8]:
import numpy as np
from sklearn.linear_model import Ridge

# Dados de exemplo
X = np.random.rand(100, 2)  # 100 exemplos, 2 features
y = np.random.rand(100)  # 100 valores alvo

# Aplicar Ridge Regression com regularização L2
modelo = Ridge(alpha=1.0)
modelo.fit(X, y)

print(modelo.coef_)

[-0.09073072 -0.04765239]


A.10. Selecionar as features úteis para o modelo usando uma das três técnicas: Filtragem, Wrapper e Embedding

- **Filtragem:** Seleciona as features com base em estatísticas univariadas, como a correlação.
- **Wrapper:** Usa um modelo de machine learning para avaliar a importância de cada subset de features.
- **Embedding:** As features são selecionadas durante o treinamento do modelo, como nos modelos baseados em árvores.

**Exemplo em Python (Filtragem):**

In [9]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, f_classif

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Selecionar as 2 melhores features
selector = SelectKBest(score_func=f_classif, k=2)
X_novas = selector.fit_transform(X, y)

print(X_novas)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

A. Manipular dados numéricos para algoritmos de Machine Learning

A.1. Explicar o que é uma feature e a sua relação com os modelos de machine learning

**Definição:** 
Uma feature, ou característica, é uma variável de entrada usada por um modelo de machine learning para fazer previsões ou tomar decisões. As features são essenciais porque carregam a informação a partir da qual o modelo aprende. Em termos mais práticos, as features podem ser vistas como colunas em uma tabela de dados, onde cada coluna representa um tipo específico de informação (como altura, peso, idade, etc.) que pode ser usada para prever um resultado (como o risco de uma doença, a classificação de um documento, etc.). A escolha e a qualidade das features influenciam diretamente o desempenho do modelo.

**Exercício Prático:**
1. Crie um dataset fictício com pelo menos 5 features (colunas) e 100 exemplos (linhas).
2. Escolha uma variável alvo e descreva como cada feature pode potencialmente influenciar a variável alvo.
3. Utilize um algoritmo de regressão linear para treinar um modelo utilizando as features e avalie a performance.

A.2. Explicar o que são escalares, vetores e espaços

**Definição:**
- **Escalares:** Um escalar é um único número real ou complexo. Em machine learning, um escalar pode representar uma única medida ou valor, como a temperatura em um dado dia.
- **Vetores:** Um vetor é uma sequência de números (escalares) dispostos em uma determinada ordem. Em machine learning, vetores são frequentemente usados para representar exemplos de dados. Por exemplo, um vetor pode representar as características (features) de um paciente, como [idade, peso, pressão arterial].
- **Espaços:** Um espaço, especificamente um espaço vetorial, é um conjunto de vetores que podem ser adicionados uns aos outros e multiplicados por escalares para formar novos vetores dentro do mesmo espaço. Em machine learning, o espaço vetorial das features é onde as operações de modelagem acontecem. Este espaço pode ser de alta dimensão dependendo do número de features usadas.

**Exercício Prático:**
1. Crie uma lista de 10 números aleatórios (escalars).
2. Transforme essa lista em um vetor.
3. Adicione dois vetores e multiplique um vetor por um escalar.
4. Visualize os vetores em um gráfico (se forem de 2 ou 3 dimensões) para melhor compreensão do espaço vetorial.

A.3. Realizar discretização de variáveis contínuas por meio de quantização com bins fixos

**Definição:**
A discretização de variáveis contínuas é o processo de converter variáveis contínuas em variáveis discretas dividindo o intervalo contínuo em partes distintas chamadas "bins". Isso pode ser feito de várias maneiras, uma das quais é utilizando bins de largura fixa.

**Exemplo em Python:**

In [ ]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com bins de largura fixa
bins = np.linspace(0, 100, 11)  # 10 bins de largura 10
labels = [f'Bin {i}' for i in range(1, len(bins))]
dados_discretizados = pd.cut(dados, bins=bins, labels=labels)

print(dados_discretizados)

**Exercício Prático:**
1. Gere um conjunto de 200 valores contínuos aleatórios.
2. Aplique a discretização com bins de largura fixa de modo que os valores sejam divididos em 5 categorias.
3. Plote um histograma dos valores antes e depois da discretização.

A.4. Realizar discretização de variáveis contínuas por meio de quantização com bins variáveis

**Definição:**
A discretização com bins variáveis, ou "quantiles", divide os dados em intervalos de tal forma que cada bin contém aproximadamente o mesmo número de pontos de dados.

**Exemplo em Python:**

In [ ]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com quantiles
dados_discretizados = pd.qcut(dados, q=10, labels=False)

print(dados_discretizados)

**Exercício Prático:**
1. Utilize o mesmo conjunto de dados do exercício anterior.
2. Aplique a discretização utilizando quantiles de forma que os dados sejam divididos em 4 categorias.
3. Compare os resultados da discretização com bins fixos e quantiles utilizando gráficos.

A.5. Utilizar a FunctionTransformer do sklearn em uma variável

**Definição:**
A `FunctionTransformer` permite transformar os dados aplicando uma função customizada. Pode ser útil para aplicar transformações que não estão diretamente disponíveis nas outras classes de transformação do scikit-learn.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Dados de exemplo
dados = np.array([[1, 2], [3, 4], [5, 6]])

# Função customizada: quadrado dos valores
transformer = FunctionTransformer(np.square)
dados_transformados = transformer.transform(dados)

print(dados_transformados)

**Exercício Prático:**
1. Crie um conjunto de dados com 3 features e 50 exemplos.
2. Aplique uma função personalizada de transformação (exemplo: logaritmo) utilizando `FunctionTransformer`.
3. Verifique o resultado e plote os dados antes e depois da transformação.

A.6. Utilizar a PowerTransformer do sklearn em uma variável

**Definição:**
A `PowerTransformer` aplica uma transformação de potência (Box-Cox ou Yeo-Johnson) para estabilizar a variância e tornar os dados mais gaussianos.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Dados de exemplo
dados = np.random.rand(100, 1) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar PowerTransformer
pt = PowerTransformer(method='yeo-johnson')
dados_transformados = pt.fit_transform(dados)

print(dados_transformados)

**Exercício Prático:**
1. Gere um conjunto de dados com distribuição não normal.
2. Aplique a transformação `PowerTransformer` e verifique a distribuição resultante.
3. Compare a distribuição dos dados antes e depois da transformação utilizando gráficos.

A.7. Utilizar a normalização Min-Max do sklearn para garantir que os dados estão na mesma faixa-dinâmica

**Definição:**
A normalização Min-Max escala os dados para que todos os valores fiquem dentro de um intervalo especificado, geralmente [0, 1].

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Min-Max Scaler
scaler = MinMaxScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

**Exercício Prático:**
1. Crie um conjunto de dados com 5 features e 200 exemplos.
2. Aplique a normalização Min-Max para garantir que todos os dados estão na faixa [0, 1].
3. Plote um gráfico de cada feature antes e depois da normalização.

A.8. Utilizar a normalização Standard Scaler

**Definição:**
A normalização com `StandardScaler` remove a média e escala os dados para que tenham desvio padrão unitário.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Standard Scaler
scaler = StandardScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

**Exercício Prático:**
1. Crie um conjunto de dados com 4 features e 150 exemplos.
2. Aplique a normalização `StandardScaler`.
3. Verifique a média e o desvio padrão dos dados antes e depois da normalização.

A.9. Utilizar a regularização norma-l2

**Definição:**
A regularização L2, também conhecida como regularização de Ridge, adiciona uma penalidade igual ao quadrado da magnitude dos coeficientes ao objetivo de otimização.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.linear_model import Ridge

# Dados de exemplo
X = np.random.rand(100, 2)  # 100 exemplos, 2 features
y = np.random.rand(100)  # 100 valores alvo

# Aplicar Ridge Regression com regularização L2
modelo = Ridge(alpha=1.0)
modelo.fit(X, y)

print(modelo.coef_)

**Exercício Prático:**
1. Gere um conjunto de dados com 3 features e 100 exemplos.
2. Aplique a regularização L2 utilizando `Ridge`.
3. Compare os coeficientes do modelo com e sem regularização.

A.10. Selecionar as features úteis para o modelo usando uma das três

 técnicas: Filtragem, Wrapper e Embedding

**Definição:**
- **Filtragem:** Seleciona as features com base em estatísticas univariadas, como a correlação.
- **Wrapper:** Usa um modelo de machine learning para avaliar a importância de cada subset de features.
- **Embedding:** As features são selecionadas durante o treinamento do modelo, como nos modelos baseados em árvores.

**Exemplo em Python (Filtragem):**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, f_classif

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Selecionar as 2 melhores features
selector = SelectKBest(score_func=f_classif, k=2)
X_novas = selector.fit_transform(X, y)

print(X_novas)

**Exercício Prático:**
1. Utilize um dataset disponível no sklearn (ex: Iris).
2. Aplique as três técnicas de seleção de features: Filtragem, Wrapper e Embedding.
3. Compare os resultados de cada técnica e discuta as vantagens e desvantagens de cada uma.
