# A. Manipular dados numéricos para algoritmos de Machine Learning

A.1. Explicar o que é uma feature e a sua relação com os modelos de machine learning

**Definição:** 
Uma feature, ou característica, é uma variável de entrada usada por um modelo de machine learning para fazer previsões ou tomar decisões. As features são essenciais porque carregam a informação a partir da qual o modelo aprende. Em termos mais práticos, as features podem ser vistas como colunas em uma tabela de dados, onde cada coluna representa um tipo específico de informação (como altura, peso, idade, etc.) que pode ser usada para prever um resultado (como o risco de uma doença, a classificação de um documento, etc.). A escolha e a qualidade das features influenciam diretamente o desempenho do modelo.

**Exercício Prático:**
1. Crie um dataset fictício com pelo menos 5 features (colunas) e 100 exemplos (linhas).
2. Escolha uma variável alvo e descreva como cada feature pode potencialmente influenciar a variável alvo.
3. Utilize um algoritmo de regressão linear para treinar um modelo utilizando as features e avalie a performance.

A.2. Explicar o que são escalares, vetores e espaços

**Definição:**
- **Escalares:** Um escalar é um único número real ou complexo. Em machine learning, um escalar pode representar uma única medida ou valor, como a temperatura em um dado dia.
- **Vetores:** Um vetor é uma sequência de números (escalares) dispostos em uma determinada ordem. Em machine learning, vetores são frequentemente usados para representar exemplos de dados. Por exemplo, um vetor pode representar as características (features) de um paciente, como [idade, peso, pressão arterial].
- **Espaços:** Um espaço, especificamente um espaço vetorial, é um conjunto de vetores que podem ser adicionados uns aos outros e multiplicados por escalares para formar novos vetores dentro do mesmo espaço. Em machine learning, o espaço vetorial das features é onde as operações de modelagem acontecem. Este espaço pode ser de alta dimensão dependendo do número de features usadas.

**Exercício Prático:**
1. Crie uma lista de 10 números aleatórios (escalars).
2. Transforme essa lista em um vetor.
3. Adicione dois vetores e multiplique um vetor por um escalar.
4. Visualize os vetores em um gráfico (se forem de 2 ou 3 dimensões) para melhor compreensão do espaço vetorial.

A.3. Realizar discretização de variáveis contínuas por meio de quantização com bins fixos

**Definição:**
A discretização de variáveis contínuas é o processo de converter variáveis contínuas em variáveis discretas dividindo o intervalo contínuo em partes distintas chamadas "bins". Isso pode ser feito de várias maneiras, uma das quais é utilizando bins de largura fixa.

**Exemplo em Python:**

In [ ]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com bins de largura fixa
bins = np.linspace(0, 100, 11)  # 10 bins de largura 10
labels = [f'Bin {i}' for i in range(1, len(bins))]
dados_discretizados = pd.cut(dados, bins=bins, labels=labels)

print(dados_discretizados)

['Bin 4', 'Bin 10', 'Bin 2', 'Bin 7', 'Bin 6', ..., 'Bin 9', 'Bin 3', 'Bin 10', 'Bin 2', 'Bin 3']
Length: 100
Categories (10, object): ['Bin 1' < 'Bin 2' < 'Bin 3' < 'Bin 4' ... 'Bin 7' < 'Bin 8' < 'Bin 9' < 'Bin 10']


**Exercício Prático:**
1. Gere um conjunto de 200 valores contínuos aleatórios.
2. Aplique a discretização com bins de largura fixa de modo que os valores sejam divididos em 5 categorias.
3. Plote um histograma dos valores antes e depois da discretização.

A.4. Realizar discretização de variáveis contínuas por meio de quantização com bins variáveis

**Definição:**
A discretização com bins variáveis, ou "quantiles", divide os dados em intervalos de tal forma que cada bin contém aproximadamente o mesmo número de pontos de dados.

**Exemplo em Python:**

In [ ]:
import numpy as np
import pandas as pd

# Dados de exemplo
dados = np.random.rand(100) * 100  # 100 valores aleatórios entre 0 e 100

# Discretização com quantiles
dados_discretizados = pd.qcut(dados, q=10, labels=False)

print(dados_discretizados)

[3 7 9 5 7 2 2 4 1 4 6 4 9 6 5 1 6 3 6 3 8 2 9 7 1 4 3 6 0 8 4 1 0 2 5 8 4
 8 0 8 5 9 4 4 2 3 3 8 9 7 2 7 6 7 1 5 3 4 8 0 2 1 6 9 2 5 3 5 6 1 0 8 9 8
 0 6 6 1 7 0 0 5 5 0 5 0 9 4 3 1 2 9 7 7 3 2 7 1 8 9]


**Exercício Prático:**
1. Utilize o mesmo conjunto de dados do exercício anterior.
2. Aplique a discretização utilizando quantiles de forma que os dados sejam divididos em 4 categorias.
3. Compare os resultados da discretização com bins fixos e quantiles utilizando gráficos.

A.5. Utilizar a FunctionTransformer do sklearn em uma variável

**Definição:**
A `FunctionTransformer` permite transformar os dados aplicando uma função customizada. Pode ser útil para aplicar transformações que não estão diretamente disponíveis nas outras classes de transformação do scikit-learn.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Dados de exemplo
dados = np.array([[1, 2], [3, 4], [5, 6]])

# Função customizada: quadrado dos valores
transformer = FunctionTransformer(np.square)
dados_transformados = transformer.transform(dados)

print(dados_transformados)

[[ 1  4]
 [ 9 16]
 [25 36]]


**Exercício Prático:**
1. Crie um conjunto de dados com 3 features e 50 exemplos.
2. Aplique uma função personalizada de transformação (exemplo: logaritmo) utilizando `FunctionTransformer`.
3. Verifique o resultado e plote os dados antes e depois da transformação.

A.6. Utilizar a PowerTransformer do sklearn em uma variável

**Definição:**
A `PowerTransformer` aplica uma transformação de potência (Box-Cox ou Yeo-Johnson) para estabilizar a variância e tornar os dados mais gaussianos.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

# Dados de exemplo
dados = np.random.rand(100, 1) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar PowerTransformer
pt = PowerTransformer(method='yeo-johnson')
dados_transformados = pt.fit_transform(dados)

print(dados_transformados)

[[ 1.45653675e+00]
 [-1.82435019e+00]
 [-9.74997502e-01]
 [-2.72559394e-01]
 [-6.45741234e-01]
 [ 1.29190322e+00]
 [-9.39048694e-02]
 [ 1.15238891e+00]
 [ 1.36291075e+00]
 [ 9.36167203e-01]
 [-3.74662199e-01]
 [-1.03632417e+00]
 [-1.42629302e+00]
 [-6.53198590e-01]
 [ 1.22477183e+00]
 [ 1.37947660e+00]
 [-1.24147814e+00]
 [ 1.23635477e+00]
 [-6.76369310e-01]
 [ 7.39119092e-01]
 [ 7.77026622e-01]
 [-1.27181005e+00]
 [-1.53748721e+00]
 [ 4.76657682e-01]
 [-1.06960942e+00]
 [ 5.83230891e-01]
 [-2.05406383e+00]
 [-1.00435901e+00]
 [ 4.97739326e-02]
 [-8.67619049e-01]
 [-4.82841095e-01]
 [-1.00079808e+00]
 [ 7.47636250e-01]
 [ 8.20980686e-01]
 [ 1.40522330e+00]
 [-2.01638121e-01]
 [-1.22146410e+00]
 [-3.94797066e-03]
 [ 2.58273465e-01]
 [ 8.60826086e-01]
 [ 2.80470006e-01]
 [-1.63284638e+00]
 [ 4.68326496e-01]
 [-9.93022340e-01]
 [ 1.31821466e-01]
 [ 2.85506796e-01]
 [ 3.50278650e-01]
 [ 1.19718627e+00]
 [ 1.36014655e+00]
 [ 7.06070353e-01]
 [ 4.26983477e-01]
 [ 8.04301224e-01]
 [ 1.3533883

**Exercício Prático:**
1. Gere um conjunto de dados com distribuição não normal.
2. Aplique a transformação `PowerTransformer` e verifique a distribuição resultante.
3. Compare a distribuição dos dados antes e depois da transformação utilizando gráficos.

A.7. Utilizar a normalização Min-Max do sklearn para garantir que os dados estão na mesma faixa-dinâmica

**Definição:**
A normalização Min-Max escala os dados para que todos os valores fiquem dentro de um intervalo especificado, geralmente [0, 1].

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Min-Max Scaler
scaler = MinMaxScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

[[0.29698611 0.10131713]
 [0.84218935 0.58740665]
 [0.01393669 0.67787934]
 [0.91983724 0.22772782]
 [0.33325783 0.91391518]
 [0.22139522 0.88321287]
 [0.89802505 0.79096503]
 [0.01739458 0.        ]
 [0.03962041 0.91855289]
 [0.39311509 0.81157749]
 [0.85543406 0.37412604]
 [0.01095799 0.64591742]
 [0.72961907 0.90522403]
 [0.413428   1.        ]
 [1.         0.55101298]
 [0.10129934 0.82613002]
 [0.76817836 0.59267065]
 [0.72132348 0.57389458]
 [0.13408622 0.34371317]
 [0.56792612 0.43821496]
 [0.17762362 0.55813523]
 [0.42666124 0.4249088 ]
 [0.63752153 0.33122103]
 [0.67129077 0.07545131]
 [0.74561449 0.880712  ]
 [0.43290372 0.35923663]
 [0.25584839 0.29364086]
 [0.25340281 0.90987125]
 [0.36597624 0.13732499]
 [0.08809685 0.19048659]
 [0.73687043 0.77375753]
 [0.11516257 0.66381707]
 [0.5901634  0.76553509]
 [0.41150813 0.43221633]
 [0.94858418 0.18344251]
 [0.82053708 0.36083571]
 [0.49786864 0.78141805]
 [0.19462497 0.70113357]
 [0.3625377  0.43515021]
 [0.11148282 0.35766022]


**Exercício Prático:**
1. Crie um conjunto de dados com 5 features e 200 exemplos.
2. Aplique a normalização Min-Max para garantir que todos os dados estão na faixa [0, 1].
3. Plote um gráfico de cada feature antes e depois da normalização.

A.8. Utilizar a normalização Standard Scaler

**Definição:**
A normalização com `StandardScaler` remove a média e escala os dados para que tenham desvio padrão unitário.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Dados de exemplo
dados = np.random.rand(100, 2) * 100  # 100 valores aleatórios entre 0 e 100

# Aplicar Standard Scaler
scaler = StandardScaler()
dados_normalizados = scaler.fit_transform(dados)

print(dados_normalizados)

[[-1.26517031 -1.39901454]
 [ 0.69799621 -1.15064596]
 [-0.28488611  0.38551224]
 [-0.28160839 -1.50587895]
 [-0.25203402 -1.38391832]
 [ 1.30016212 -0.93320835]
 [ 0.61741627  0.53526383]
 [ 0.34362279  0.52013077]
 [ 0.17258852 -0.57604318]
 [-1.19330841 -1.09294466]
 [-0.7316898   0.65618369]
 [-1.67301997 -1.20708213]
 [ 1.65663452  0.71144846]
 [ 0.38648702  1.71268979]
 [-0.81371849 -0.68329061]
 [ 1.81953518  1.80997868]
 [-0.13677057  1.43581202]
 [-0.44860312  0.53591838]
 [ 1.44712613  0.0714877 ]
 [-0.05006525 -0.77449562]
 [-0.19458469  0.05655599]
 [-0.47875935  1.43705797]
 [-0.63467732  1.47242839]
 [-0.80267103  0.76965657]
 [-0.5628952  -1.25965895]
 [ 1.4435346  -0.43340833]
 [ 0.670104   -0.28474601]
 [-0.17187753 -1.2479676 ]
 [ 0.47271183 -0.6835328 ]
 [-1.09593668  1.21243013]
 [-0.81934376  1.65078761]
 [ 0.45928259 -0.3540111 ]
 [-0.97978055 -1.29777272]
 [ 1.51274945 -0.98830472]
 [-1.35914474 -1.15653657]
 [ 1.58649522 -1.45642711]
 [ 1.08215761  0.34169941]
 

**Exercício Prático:**
1. Crie um conjunto de dados com 4 features e 150 exemplos.
2. Aplique a normalização `StandardScaler`.
3. Verifique a média e o desvio padrão dos dados antes e depois da normalização.

A.9. Utilizar a regularização norma-l2

**Definição:**
A regularização L2, também conhecida como regularização de Ridge, adiciona uma penalidade igual ao quadrado da magnitude dos coeficientes ao objetivo de otimização.

**Exemplo em Python:**

In [ ]:
import numpy as np
from sklearn.linear_model import Ridge

# Dados de exemplo
X = np.random.rand(100, 2)  # 100 exemplos, 2 features
y = np.random.rand(100)  # 100 valores alvo

# Aplicar Ridge Regression com regularização L2
modelo = Ridge(alpha=1.0)
modelo.fit(X, y)

print(modelo.coef_)

[-0.03732184 -0.06559702]


**Exercício Prático:**
1. Gere um conjunto de dados com 3 features e 100 exemplos.
2. Aplique a regularização L2 utilizando `Ridge`.
3. Compare os coeficientes do modelo com e sem regularização.

A.10. Selecionar as features úteis para o modelo usando uma das três

 técnicas: Filtragem, Wrapper e Embedding

**Definição:**
- **Filtragem:** Seleciona as features com base em estatísticas univariadas, como a correlação.
- **Wrapper:** Usa um modelo de machine learning para avaliar a importância de cada subset de features.
- **Embedding:** As features são selecionadas durante o treinamento do modelo, como nos modelos baseados em árvores.

**Exemplo em Python (Filtragem):**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, f_classif

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Selecionar as 2 melhores features
selector = SelectKBest(score_func=f_classif, k=2)
X_novas = selector.fit_transform(X, y)

print(X_novas)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

**Exercício Prático:**
1. Utilize um dataset disponível no sklearn (ex: Iris).
2. Aplique as três técnicas de seleção de features: Filtragem, Wrapper e Embedding.
3. Compare os resultados de cada técnica e discuta as vantagens e desvantagens de cada uma.



## H. Selecionar as features úteis para o modelo usando uma das três técnicas: Filtragem, Wrapper e Embedding

H.1. Técnica de Filtragem

**Definição:**
A técnica de filtragem seleciona as features com base em estatísticas univariadas, como a correlação, variância ou outras métricas estatísticas, sem considerar um modelo de machine learning específico. 

**Exemplo em Python:**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, f_classif

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Selecionar as 2 melhores features
selector = SelectKBest(score_func=f_classif, k=2)
X_novas = selector.fit_transform(X, y)

print(X_novas)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

**Exercício Prático:**
1. Utilize um dataset disponível no sklearn (ex: Iris).
2. Aplique a técnica de filtragem para selecionar as melhores features.
3. Compare os resultados com o dataset original e discuta a relevância das features selecionadas.

H.2. Técnica Wrapper

**Definição:**
A técnica Wrapper utiliza um modelo de machine learning para avaliar a importância de cada subset de features. A técnica mais comum é o método de seleção recursiva de features (RFE).

**Exemplo em Python:**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Aplicar RFE com regressão logística
modelo = LogisticRegression(max_iter=200)
selector = RFE(modelo, n_features_to_select=2, step=1)
selector = selector.fit(X, y)

print("Features Selecionadas:", selector.support_)
print("Ranking das Features:", selector.ranking_)

Features Selecionadas: [False False  True  True]
Ranking das Features: [3 2 1 1]


**Exercício Prático:**
1. Utilize um dataset disponível no sklearn (ex: Iris).
2. Aplique a técnica Wrapper usando RFE para selecionar as melhores features.
3. Compare os resultados com a técnica de filtragem e discuta as vantagens e desvantagens.

H.3. Técnica Embedding

**Definição:**
A técnica Embedding seleciona as features durante o treinamento do modelo. Modelos baseados em árvores, como Random Forest, são comuns para esta técnica.

**Exemplo em Python:**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

# Carregar dados de exemplo
iris = load_iris()
X, y = iris.data, iris.target

# Aplicar Random Forest para seleção de features
modelo = RandomForestClassifier(n_estimators=100)
modelo.fit(X, y)

# Selecionar as features com base na importância
selector = SelectFromModel(modelo, prefit=True)
X_novas = selector.transform(X)

print(X_novas)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

**Exercício Prático:**
1. Utilize um dataset disponível no sklearn (ex: Iris).
2. Aplique a técnica Embedding usando Random Forest para selecionar as melhores features.
3. Compare os resultados com as técnicas de Filtragem e Wrapper e discuta as diferenças.

